/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfacegrafica;

import javax.swing.JOptionPane;
import java.util.Iterator;
import classededados.Aluno;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import persistencia.AlunoPersistenciaTemplateMethod;
import persistencia.*;

/**
 *
 * @author eugeniojulio
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGridAlunos = new javax.swing.JTable();
        jToggleButton_Ordenar_Sobrenome = new javax.swing.JToggleButton();
        jToggleButton_Ordenar_Curso_Nome = new javax.swing.JToggleButton();
        jToggleButton_Ordenar_Situacao_Nome = new javax.swing.JToggleButton();
        jToggleButton_Ordenar_Enfase_Nome = new javax.swing.JToggleButton();
        jToggleButton_Ordenar_Curso_Enfase_Nome = new javax.swing.JToggleButton();
        jToggleButton_Ordenar_Enfase_Curso_Nome = new javax.swing.JToggleButton();
        jToggleButton_Ordenar_Situacao_Curso_Nome = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LISTA DE ALUNOS");

        jTableGridAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Cusro", "Situacao", "Enfase"
            }
        ));
        jScrollPane1.setViewportView(jTableGridAlunos);

        jToggleButton_Ordenar_Sobrenome.setText("Sobrenome");
        jToggleButton_Ordenar_Sobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_Ordenar_SobrenomeActionPerformed(evt);
            }
        });

        jToggleButton_Ordenar_Curso_Nome.setText("Curso/Nome");
        jToggleButton_Ordenar_Curso_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_Ordenar_Curso_NomeActionPerformed(evt);
            }
        });

        jToggleButton_Ordenar_Situacao_Nome.setText("Situacao/Nome");
        jToggleButton_Ordenar_Situacao_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_Ordenar_Situacao_NomeActionPerformed(evt);
            }
        });

        jToggleButton_Ordenar_Enfase_Nome.setText("Enfase/Nome");
        jToggleButton_Ordenar_Enfase_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_Ordenar_Enfase_NomeActionPerformed(evt);
            }
        });

        jToggleButton_Ordenar_Curso_Enfase_Nome.setText("Curso/Enfase/Nome");
        jToggleButton_Ordenar_Curso_Enfase_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_Ordenar_Curso_Enfase_NomeActionPerformed(evt);
            }
        });

        jToggleButton_Ordenar_Enfase_Curso_Nome.setText("Enfase/Curso/Nome");
        jToggleButton_Ordenar_Enfase_Curso_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_Ordenar_Enfase_Curso_NomeActionPerformed(evt);
            }
        });

        jToggleButton_Ordenar_Situacao_Curso_Nome.setText("Situacao/Curso/Nome");
        jToggleButton_Ordenar_Situacao_Curso_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_Ordenar_Situacao_Curso_NomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton_Ordenar_Sobrenome)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton_Ordenar_Curso_Nome)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton_Ordenar_Situacao_Nome)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton_Ordenar_Enfase_Nome)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton_Ordenar_Curso_Enfase_Nome)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton_Ordenar_Enfase_Curso_Nome)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton_Ordenar_Situacao_Curso_Nome)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton_Ordenar_Sobrenome)
                    .addComponent(jToggleButton_Ordenar_Curso_Nome)
                    .addComponent(jToggleButton_Ordenar_Situacao_Nome)
                    .addComponent(jToggleButton_Ordenar_Enfase_Nome)
                    .addComponent(jToggleButton_Ordenar_Curso_Enfase_Nome)
                    .addComponent(jToggleButton_Ordenar_Enfase_Curso_Nome)
                    .addComponent(jToggleButton_Ordenar_Situacao_Curso_Nome))
                .addGap(164, 164, 164)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void imprimirNaGrid(ArrayList<Aluno> dados){
        try{
            DefaultTableModel model =  (DefaultTableModel) jTableGridAlunos.getModel();
            model.setNumRows(0);
            int pos = 0;
            while(pos < dados.size()){
                String[] linha = new String[4];
                Aluno obj = dados.get(pos);
                linha[0]= obj.getNome();
                linha[1]= obj.getCurso();
                linha[2]= obj.getSituacao();
                linha[3]= obj.getEnfase();
                model.addRow(linha);
                pos++;
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }
    private void jToggleButton_Ordenar_SobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_Ordenar_SobrenomeActionPerformed
        // TODO add your handling code here:
        try{
            
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenadoPorNome objeto = new OrdenadoPorNome(nome);
            imprimirNaGrid(objeto.listagemDeAlunosNome());
            
           
            
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jToggleButton_Ordenar_SobrenomeActionPerformed

    private void jToggleButton_Ordenar_Curso_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_Ordenar_Curso_NomeActionPerformed
        // TODO add your handling code here:
            try{
            
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenadoPorCurso_Nome objeto = new OrdenadoPorCurso_Nome(nome);
            imprimirNaGrid(objeto.listagemDeAlunosNome());
            
           
            
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    
    }//GEN-LAST:event_jToggleButton_Ordenar_Curso_NomeActionPerformed

    private void jToggleButton_Ordenar_Situacao_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_Ordenar_Situacao_NomeActionPerformed
        // TODO add your handling code here:
           try{
            
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenadoPorSituacao_Nome objeto = new OrdenadoPorSituacao_Nome(nome);
            imprimirNaGrid(objeto.listagemDeAlunosNome());
            
           
            
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    
    }//GEN-LAST:event_jToggleButton_Ordenar_Situacao_NomeActionPerformed

    private void jToggleButton_Ordenar_Enfase_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_Ordenar_Enfase_NomeActionPerformed
        // TODO add your handling code here:
         try{
            
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenadoPorEnfase_Nome objeto = new OrdenadoPorEnfase_Nome(nome);
            imprimirNaGrid(objeto.listagemDeAlunosNome());
            
           
            
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jToggleButton_Ordenar_Enfase_NomeActionPerformed

    private void jToggleButton_Ordenar_Curso_Enfase_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_Ordenar_Curso_Enfase_NomeActionPerformed
        // TODO add your handling code here:
        try{
            
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenadoPorCurso_Enfase_Nome objeto = new OrdenadoPorCurso_Enfase_Nome(nome);
            imprimirNaGrid(objeto.listagemDeAlunosNome());
            
           
            
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jToggleButton_Ordenar_Curso_Enfase_NomeActionPerformed

    private void jToggleButton_Ordenar_Enfase_Curso_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_Ordenar_Enfase_Curso_NomeActionPerformed
        // TODO add your handling code here:
        try{
            
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenadoPorEnfase_Curso_Nome objeto = new OrdenadoPorEnfase_Curso_Nome(nome);
            imprimirNaGrid(objeto.listagemDeAlunosNome());
            
           
            
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jToggleButton_Ordenar_Enfase_Curso_NomeActionPerformed

    private void jToggleButton_Ordenar_Situacao_Curso_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_Ordenar_Situacao_Curso_NomeActionPerformed
        // TODO add your handling code here:
       try{
            
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenadoPorSituacao_Curso_Nome objeto = new OrdenadoPorSituacao_Curso_Nome(nome);
            imprimirNaGrid(objeto.listagemDeAlunosNome());
            
           
            
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        } 
    }//GEN-LAST:event_jToggleButton_Ordenar_Situacao_Curso_NomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableGridAlunos;
    private javax.swing.JToggleButton jToggleButton_Ordenar_Curso_Enfase_Nome;
    private javax.swing.JToggleButton jToggleButton_Ordenar_Curso_Nome;
    private javax.swing.JToggleButton jToggleButton_Ordenar_Enfase_Curso_Nome;
    private javax.swing.JToggleButton jToggleButton_Ordenar_Enfase_Nome;
    private javax.swing.JToggleButton jToggleButton_Ordenar_Situacao_Curso_Nome;
    private javax.swing.JToggleButton jToggleButton_Ordenar_Situacao_Nome;
    private javax.swing.JToggleButton jToggleButton_Ordenar_Sobrenome;
    // End of variables declaration//GEN-END:variables
}
